### ISSUE TITLE
Klipper Screen stuck on Login Console

### ISSUE THREAD

**Issue by Doormat1** [bigtreetech/TFT35-SPI#4]
I have the screen attached to a Manta E3 EZ and a CB1. I have installed klipper screen using KIAUH and all I get is the log in screen and nothing more. I have checked the logs and it is saying no screens found. Any suggestions?

**Comment by clsferguson** [comment]
did you resolve this? I have this issue right now.

**Comment by Doormat1** [comment]
Yes. Did a clean instal of the minimal kernel from btt and then used kiauh to install klipper, mainsail et Al and it worked fine

**Comment by clsferguson** [comment]
that sucks.. Well I guess its probably faster to try then waiting on anyone to get back to me.

**Comment by clsferguson** [comment]
Ok, so I think I resolved it, I kind of got lucky, I was about to reflash the OS. I installed kiauh. Then I removed KlipperScreen, reinstalled it. I did a host reboot, the issue was still present. So, I shut it down. Then I remembered to copy my printer.cfg. When I booted it back up again, the screen is now working.

**Comment by Doormat1** [comment]
I think my issue was a driver conflict as I had tried gpio screen first. I believe I remember having a similar issue that klipper screen only boots when klipper/mainsail has no issues.
